# Generated by Django 2.0.10 on 2019-02-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupformpagebullet',
            name='icon',
            field=models.CharField(choices=[('home/includes/svg/bulb-svg.html', 'Light bulb'), ('home/includes/svg/pro-svg.html', 'Chart'), ('home/includes/svg/tick-svg.html', 'Tick')], max_length=100),
        ),
    ]
