# Generated by Django 2.0 on 2019-01-26 12:01

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_jobindexpage_jobindexpagejob_reasontojoin_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobindexpagejob',
            name='page',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='home.JobIndexPage'),
            preserve_default=False,
        ),
    ]
