# Generated by Django 2.0 on 2019-01-26 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_contactlandingpagerelatedlinkbutton'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdGrantsPageGrantsManaged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.homeImage')),
            ],
        ),
    ]
