# Generated by Django 2.0 on 2019-01-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_googleadgrantspagegrantsmanaged'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdGrantsPageQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.TextField()),
                ('person_name', models.CharField(max_length=255)),
                ('organisation_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
