# Generated by Django 2.0 on 2019-01-26 13:04

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0015_googleadgrantspagequote'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdGrantsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.core.fields.RichTextField()),
                ('form_title', models.CharField(max_length=255)),
                ('form_subtitle', models.CharField(max_length=255)),
                ('form_button_text', models.CharField(max_length=255)),
                ('to_address', models.EmailField(blank=True, help_text='Optional - form submissions will be emailed to this address', max_length=254, verbose_name='to address')),
                ('body', wagtail.core.fields.RichTextField()),
                ('grants_managed_title', models.CharField(max_length=255)),
                ('call_to_action_title', models.CharField(blank=True, max_length=255)),
                ('call_to_action_embed_url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
