# Generated by Django 2.0 on 2019-01-26 13:12

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_googleadgrantspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleadgrantspagegrantsmanaged',
            name='page',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grants_managed', to='home.GoogleAdGrantsPage'),
            preserve_default=False,
        ),
    ]
