# Generated by Django 2.0.10 on 2019-02-02 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_author'),
        ('home', '0020_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='contact_person',
            field=models.ForeignKey(help_text='Ensure this person has telephone and email fields set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.PersonPage'),
        ),
    ]
