# Generated by Django 2.0.10 on 2019-02-03 07:51

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_globalsettings_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='menu',
            field=wagtail.core.fields.StreamField((('items', wagtail.core.blocks.StructBlock((('page', wagtail.core.blocks.PageChooserBlock()), ('subitems', wagtail.core.blocks.StreamBlock((('subitem', wagtail.core.blocks.PageChooserBlock()),), blank=True))))),), blank=True),
        ),
    ]
