# Generated by Django 2.0.10 on 2019-02-03 09:46

from django.db import migrations
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20190203_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='menu',
            field=wagtail.core.fields.StreamField((('items', wagtail.core.blocks.StructBlock((('page', wagtail.core.blocks.PageChooserBlock()), ('subitems', wagtail.core.blocks.StreamBlock((('subitem', wagtail.core.blocks.PageChooserBlock()),), blank=False, null=True, on_delete=django.db.models.deletion.SET_NULL))))),), blank=True),
        ),
    ]
