# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20190204_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeimage',
            name='file_hash',
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='menu',
            field=wagtail.core.fields.StreamField([('items', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock()), ('subitems', wagtail.core.blocks.StreamBlock([('subitem', wagtail.core.blocks.PageChooserBlock(blank=True))], required=False))], blank=True))], blank=True),
        ),
    ]
