# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 16:59
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20190204_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='menu',
            field=wagtail.core.fields.StreamField([('items', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock()), ('subitems', wagtail.core.blocks.StreamBlock([('subitem', wagtail.core.blocks.PageChooserBlock())], required=False))]))], blank=True),
        ),
    ]
