# Generated by Django 2.0 on 2019-02-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20190204_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeimage',
            name='file_hash',
        ),
    ]
